name: basic_utils
description: Common util classes providing a solution for different situations.
version: 2.3.0
homepage: https://github.com/Ephenodrom/Dart-Basic-Utils
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  logging: ^0.11.3+2
  json_annotation: ^3.0.0
  pointycastle: ^1.0.1
  asn1lib: ^0.5.13
  convert: ^2.1.1
  crypto: ^2.1.3


dev_dependencies:
  test: '>=0.12.42 <2.0.0'
  build_runner: ^1.5.0
  json_serializable: ^3.2.2