name: basic_utils
description: Common util classes providing a solution for different situations.
version: 5.4.3
homepage: https://github.com/Ephenodrom/Dart-Basic-Utils
#publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  http: ^0.13.5
  logging: ^1.1.1
  json_annotation: ^4.6.0
  pointycastle: ^3.6.2

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.0.1
  test: ^1.22.2
  convert: ^3.1.1

false_secrets:
 - /test/crypto_utils_test.dart
