name: basic_utils
description: Common util classes providing a solution for different situations.
version: 3.5.0
homepage: https://github.com/Ephenodrom/Dart-Basic-Utils
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  logging: ^1.0.1
  json_annotation: ^4.0.0
  pointycastle: ^3.2.0

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  pedantic: ^1.10.0
  test: ^1.16.8
  convert: ^3.0.0