name: basic_utils
description: Common util classes providing a solution for different situations.
version: 1.0.3
author: Daniel Linsenmeier <daniel@ephenodrom.de>
homepage: https://github.com/Ephenodrom/Dart-Basic-Utils
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: 0.12.0
  logging: ^0.11.3+2


dev_dependencies:
  test: '>=0.12.42 <2.0.0'